### ISSUE TITLE
enable-auto-merge doesn't work

### ISSUE THREAD

**Issue by sensuikan1973** [sensuikan1973/libedax4dart#497]
```
Run gh pr merge -R "sensuikan1973/libedax4dart" --squash --auto "496"
  gh pr merge -R "sensuikan[19](https://github.com/sensuikan1973/libedax4dart/actions/runs/7717379727/job/21036367593#step:9:21)73/libedax4dart" --squash --auto "496"
  shell: /bin/bash --noprofile --norc -e -o pipefail {0}
  env:
    DART_HOME: /Users/runner/hostedtoolcache/dart/3.2.6/x64
    PUB_CACHE: /Users/runner/.pub-cache
    PULL_REQUEST_NUMBER: 496
    GH_TOKEN: ***
GraphQL: Field 'isMergeQueueEnabled' doesn't exist on type 'PullRequest' (query PullRequestByNumber.repository.pullRequest.isMergeQueueEnabled)
```
